<?php declare(strict_types=1);

namespace Symfony\Component\Config\Definition\Configurator;

use danielburger1337\BffProxyBundle\BffProxyBundle;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\StreamFactoryInterface;

return static function (DefinitionConfigurator $definition): void {
    $definition
        ->rootNode()
            ->children()
                ->scalarNode('local_proxy')
                    ->treatFalseLike(null)
                    ->treatTrueLike('local')
                    ->info('Path prefix to proxy local requests.')
                    ->defaultNull()
                ->end()
                ->scalarNode('options_parameter')
                    ->info('Query parameter to configure runtime behaviour of the BFF proxy.')
                    ->cannotBeEmpty()
                    ->defaultValue('bff_proxy')
                ->end()
                ->arrayNode('upstreams')
                    ->defaultValue([])
                    ->normalizeKeys(false)
                    ->prototype('array')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('http_client')
                                ->info('PSR18 http client that will send the proxied request.')
                                ->cannotBeEmpty()
                                ->defaultValue(ClientInterface::class)
                            ->end()
                            ->scalarNode('request_factory')
                                ->info('PSR17 request factory.')
                                ->cannotBeEmpty()
                                ->defaultValue(RequestFactoryInterface::class)
                            ->end()
                            ->scalarNode('stream_factory')
                                ->info('PSR17 stream factory.')
                                ->cannotBeEmpty()
                                ->defaultValue(StreamFactoryInterface::class)
                            ->end()
                            ->scalarNode('http_foundation_factory')
                                ->info('Service that converts PSR7 messages to http-foundation objects.')
                                ->cannotBeEmpty()
                                ->defaultValue(BffProxyBundle::SERVICE_ID_HTTP_FOUNDATION_FACTORY)
                            ->end()
                            ->booleanNode('passthrough_request_x_headers')
                                ->info('Forward all headers that start with "X-" to the upstream')
                                ->defaultFalse()
                            ->end()
                            ->arrayNode('passthrough_request_headers')
                                ->info('Forward specific headers to the upstream')
                                ->prototype('scalar')->end()
                                ->defaultValue([])
                            ->end()
                            ->booleanNode('passthrough_response_x_headers')
                                ->info('Automatically passthrough headers that start with "X-"')
                                ->defaultFalse()
                            ->end()
                            ->arrayNode('passthrough_response_headers')
                                ->info('Headers that will be extracted from the response and added to the http-foundation response.')
                                ->prototype('scalar')->end()
                                ->defaultValue([])
                            ->end()
                            ->booleanNode('support_file_upload')
                                ->info('Support file uploads via multipart/form-data. This may use more memory.')
                                ->defaultTrue()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
